[[feeds]]
name = "nixos-unstable"
delay_minutes = 2
source = "nixpkgs"
kind = "github_api"


[[feeds]]
name = "master"
delay_minutes = 2
source = "nixpkgs"
kind = "github_atom"

[[feeds]]
name = "nixos-26.05"
delay_minutes = 2
source = "nixpkgs"
kind = "github_atom"

[general]
database_path = "tmp/database.db"
